### ISSUE TITLE
[blocked] Add sanctions screening

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#114]
https://www.chainalysis.com/free-cryptocurrency-sanctions-screening-tools/

**Comment by jahabeebs** [comment]
@pi0neerpat chainalysis blocks all my requests unless I disable CORS, so we need to call their endpoint from an API. currently we're using apollo client and initialize it like this:

```
export const client = new ApolloClient({
    uri: 'https://subgraph.reflexer.finance/subgraphs/name/reflexer-labs/rai',
    cache: new InMemoryCache(),
})
```
should we set up our own standalone express server for making REST calls? or initialize another apollo client using the chainalysis endpoint?

**Comment by jahabeebs** [comment]
still getting CORS issues so re-opening

**Comment by jahabeebs** [comment]
> https://www.chainalysis.com/free-cryptocurrency-sanctions-screening-tools/

@pi0neerpat Chainalysis confirmed they don't allow the API to be called from the browser

**Comment by pi0neerpat** [comment]
Only allowed to call from the server
