### ISSUE TITLE
Add New Address/Token Header Component

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#159]
prototype: https://www.figma.com/proto/uJdTlxdVIJNozrmGtqQQvq/OpenDollar-App?page-id=480%3A423&type=design&node-id=480-424&viewport=569%2C360%2C0.29&t=bAI7uWFqWEmEUt3C-8&scaling=min-zoom&starting-point-node-id=480%3A424&hide-ui=1

image 

![image](https://github.com/open-dollar/od-app/assets/47253537/dc74b7df-562c-4f67-beb6-040946f38700)

**Comment by pi0neerpat** [comment]
![image](https://github.com/open-dollar/od-app/assets/35622595/398a5f95-6fad-4553-8063-11327f264ba7)
