### ISSUE TITLE
Add SVG

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#168]
Lets come up with a plan before starting this.

- [ ] Add SVG to vault page
- [ ] Update item title (top of page) to include the collateral type eg.  `ARB Vault #1`

![image](https://github.com/open-dollar/od-app/assets/35622595/bdc444f0-1ab8-43a9-9842-466a2a3f26f8)

**Comment by jahabeebs** [comment]
> Lets come up with a plan before starting this.
> 
>     * [ ]  Add SVG to vault page
> 
>     * [ ]  Update item title (top of page) to include the collateral type eg.  `ARB Vault #1`
> 
> 
> ![image](https://user-images.githubusercontent.com/35622595/276083965-bdc444f0-1ab8-43a9-9842-466a2a3f26f8.png)


@pi0neerpat Here's my plan for the issue:


<img width="781" alt="Screenshot 2023-10-23 at 3 16 45 PM" src="https://github.com/open-dollar/od-app/assets/47253537/cf076840-0b8b-4808-8e0d-a755c0f2896a">

The designs have a lot of repetitive info --why do we have debt owed, collateral deposited, etc both next to the SVG and below it? 

I think it would be better to keep the side by side idea for now

<img width="483" alt="Screenshot 2023-10-23 at 3 18 58 PM" src="https://github.com/open-dollar/od-app/assets/47253537/78c2fbad-7485-4bf1-a521-d447bb4189f9">

What I would do is move the info from these components:

<img width="509" alt="Screenshot 2023-10-23 at 3 20 43 PM" src="https://github.com/open-dollar/od-app/assets/47253537/8c61efb0-aced-4610-98c2-ca5dd4951b38">

into this component:

<img width="285" alt="Screenshot 2023-10-23 at 3 21 09 PM" src="https://github.com/open-dollar/od-app/assets/47253537/6df578ba-c032-47c3-b6be-927646f7560a">

^ now that this component is taller we can fit our svg on the left side. 

As for adding the SVG itself, it seems that opensea has this endpoint that lets us specify a contract address and an identifier (like our safeId)

https://docs.opensea.io/reference/get_nft

I think it would be best to hit this endpoint for a given safe ID and then put the URL in an image tag to display it?
