### ISSUE TITLE
Bridge research

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#195]
## Description
I've researched around 20 bridges and narrowed it down to a few options:

1) [Squid router](https://www.squidrouter.com/) (this is my favorite option currently)
- Built on axelar, [good security](https://axelar.network/blog/security-at-axelar-core)
- Good front-end resources and SDK is easy to use (widget docs here: https://docs.widget.squidrouter.com/ and here: https://github.com/0xsquid/widget-integrations, and here: https://docs.squidrouter.com/choose-how-to-integrate)
-  37+ chains supported, used by 50+ co's like ledger, pancakeswap

Unknowns:
- Seems no sepolia support yet
- Would need to contract them about supporting tokens we want to add (they support many like wsteth here: https://v2.app.squidrouter.com/)
- Can request supporting token allowlisting here: https://form.typeform.com/to/wVLxNgSd
https://docs.squidrouter.com/

2) [Wormhole protocol](https://wormhole.com/)
- Excellent developer documentation and front-end resources, low-code focus (see https://docs.wormhole.com/wormhole/quick-start/wh-connect and https://github.com/wormhole-foundation/example-token-bridge-ui)
- Lots of audits (https://docs.wormhole.com/wormhole/explore-wormhole/security) 
- 25+ chains, customizable rpc urls
- Sepolia support: https://docs.wormhole.com/wormhole/blockchain-environments/evm#arbitrum

Unknowns:
- Arbitrum and mainnet support on 11/30
- Not sure if this protocol requires smart contract changes for compatibility? Might need to contact https://docs.wormhole.com/wormhole/quick-start/cross-chain-dev

3) Rubic finance (https://rubic.exchange/)
- 60+ chains, 16k tokens supported, 60+ dexs supported
- Great front-end resources: Widget (https://tools.rubic.exchange/widget) and SDK (https://tools.rubic.exchange/sdk)
- Customizable fees and RPCs

Unknowns: 
- Not convinced about security, certik audit + some others I don't recognize (https://docs.rubic.finance/rubic/security)
- 130+ projects using it but don't recognize these projects
- Didn't see sepolia support mentioned
- Need to request token support (https://docs.rubic.finance/integrate-widget/listing)

**Comment by pi0neerpat** [comment]
Discussion continued in Discord

**Comment by pi0neerpat** [comment]
Closing this initial round of review.

**Comment by cupOJoseph** [comment]
@pi0neerpat @jahabeebs consider the official arbitrum bridge.

- mainnet -> arb instant, takes a longer delay in the reverse
- its direct token to token, no slippage or fees. why make our customers pay more in fees? 
- only thing, you must have a tiny bit of gas on arbitrum when bridging tokens there: https://support.arbitrum.io/hc/en-gb/articles/18213854684699
