### ISSUE TITLE
Audit docker project / app build

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#214]
In #207 we were never able to see the final app. The app might not be building correctly, or some issue with the way its being served?

I have the same error locally when using the command `yarn serve -s build`

**Comment by Sintayew4** [comment]
#214

**Comment by jahabeebs** [comment]
@pi0neerpat I fixed the docker build by ensuring it pulls env variables. see my comment I made with the fix in the original PR:

https://github.com/open-dollar/od-app/pull/207

**Comment by pi0neerpat** [comment]
completed
