### ISSUE TITLE
Gas failing tx bug

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#232]
Related to #231

Transaction failures are occurring. Likely due to gas estimation too low.

- Investigate whether the gas estimation method needs to be updated
- Remove gas estimation feature completely?

**Comment by jahabeebs** [comment]
> Related to #231
> 
> Transaction failures are occurring. Likely due to gas estimation too low.
> 
>     * Investigate whether the gas estimation method needs to be updated
> 
>     * Remove gas estimation feature completely?

@pi0neerpat So there are two issues going on related to this issue and https://github.com/open-dollar/od-app/issues/231#event-11546286195:
1) cannot withdraw any collateral or repay anything without failure (doesn't matter if trying to do max or just a small value). I've tried to adjust gas by several multiples, I reverted my changes to unlock OD that adds a buffer, but still none of these go through so I think there must be a contract issue going on
2) when creating a CBETH or RETH or ARB vault, the max value is always too high for the vault to be approved 

example failure creating vault:

https://github.com/open-dollar/od-app/assets/47253537/8b10bf8c-f8f4-460a-8b6d-1208758f3701

example success creating vault:

https://github.com/open-dollar/od-app/assets/47253537/1c8d20c3-166a-4d2f-bfb6-af46f31f5f79

I'm not sure why this happens yet

**Comment by pi0neerpat** [comment]
For item 2. is the amount being padded due to the changes we made in #217? This would cause it to fail, since its greater than your balance of wstETH

**Comment by jahabeebs** [comment]
> For item 2. is the amount being padded due to the changes we made in #217? This would cause it to fail, since its greater than your balance of wstETH

Even after I revert those changes and jack up the gas it still fails immediately. It's very weird, like there's something about those collaterals themselves that are off. when I reduce the decimals by a couple tenths of a decimal I can create a vault but it's an unpredictable amount each time

**Comment by jahabeebs** [comment]
@pi0neerpat I still think for the repay problem it's a contract problem because no changes in gas have been able to fix it. However, for the create vault issue there's a band-aid fix to reduce the max amount by .2%. It seems the returnAvaiableDebt function no longer returns an accurate amount of debt that can be taken out when the vault is created.
