### ISSUE TITLE
HAI Optimism app cleanup

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#280]
- Update the explorer URLs to point to https://optimistic.etherscan.io
- Metamask is still prompting to switch to Arb Sepolia when on Optimism. Update that check to ask to switch to Optimism
- Troubleshoot why modifying a safe fails
- Test creating a safe
- Use a better method for totalSafes than the subgraph. See the hai sdk for ideas

**Comment by jahabeebs** [comment]
@pi0neerpat I've pushed up some the network fixes (wallet switches to right networks, we have explorer URLs) but haven't been able to create or modify safes with collateral yet
