### ISSUE TITLE
App Redesign: Modify Header to Match Designs

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#287]
Modify everything in the header except for the buttons (which is the task for #286) to match the new designs (drop shadow, new font color, new font sizes, add new font if necessary, etc)

The latest figma spec is here: https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=0-1&mode=design&t=bxu6vQm5wLH3eDKu-0

latest figma prototype: https://www.figma.com/proto/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?page-id=216%3A1011&type=design&node-id=216-1013&viewport=343%2C1779%2C0.52&t=H3hQQJGiQRjItRp0-1&scaling=min-zoom&starting-point-node-id=216%3A1013

<img width="1408" alt="Screenshot 2024-03-20 at 2 41 07 PM" src="https://github.com/open-dollar/od-app/assets/47253537/8f0b325e-53f9-47b8-b50c-8688d042c962">

**Comment by pi0neerpat** [comment]
Closed in #307
