### ISSUE TITLE
App Redesign: new hero section (w/vault list)

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#292]
relates to but doesn't depend on https://github.com/open-dollar/od-app/issues/291

- New create vault button, new translucent rows with vault info, new icons for treasures, new checkbox for showing empty vaults, new text spacing and colors for risk level, etc to match designs. Might need to change card component to be easy to re-use for other screens (like here and in Create Vault which will have a lot of card usage)

current design as of 4/04 but reference latest:

![image](https://github.com/open-dollar/od-app/assets/69639595/184ada62-0080-4fe3-abcf-0a96c0d6142b)

Reference:
https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=678-1122&mode=design&t=6G3HHkwuj0v3nhna-0

**Comment by alekseevaiana** [comment]
Closed by #372

**Comment by alekseevaiana** [comment]
Closed by #372
