### ISSUE TITLE
App Redesign: stats component on modify vaults page

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#293]
## Redesign with new boxes, background color, fonts, etc to match designs

current design as of 4/04 but reference latest:

### Stats Page (stats, system info, system rates):  
![image](https://github.com/open-dollar/od-app/assets/69639595/12955267-9d71-4fb5-948a-27bf27fd94c5)

### Prices Collateral:
![image](https://github.com/open-dollar/od-app/assets/69639595/f646e10c-4e8d-456d-9899-9ffb5dfa33ed)

### Contracts:
![image](https://github.com/open-dollar/od-app/assets/69639595/7ca3546a-ce35-4e7c-a77e-836caad3c4f7)

- As for mobile designs, stick with a column and 1 element per row
- The info pop-ups will contain the same text as the current site

Figma file: https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=678-1010&mode=design&t=76XX8JUUzbwAXQ7N-0

**Comment by pi0neerpat** [comment]
Closed by #356
