### ISSUE TITLE
App Redesign: Create vault page

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#297]
- Change layout, font colors, background color, card shape and shadows, etc to match designs

current design as of 4/04 but reference latest:

### Step 1
![image](https://github.com/open-dollar/od-app/assets/69639595/2a35ffe1-876d-40b1-98e7-830ab2d183ef)

### Step 2
![image](https://github.com/open-dollar/od-app/assets/69639595/2537282c-22cd-4a03-befb-7add6ab4b98e)

### Step 3
![image](https://github.com/open-dollar/od-app/assets/69639595/c1a78b37-f2fc-45d9-a974-d25ec61c0427)

Design file: https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=678-1010&mode=design&t=76XX8JUUzbwAXQ7N-0

**Comment by alekseevaiana** [comment]
Closed by #361
