### ISSUE TITLE
App Redesign: Auctions page

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#300]
- Implement new design (new button for switching between auction type, new collateral dropdown, new card and background colors, new arrow on dropdown,  new font colors and weights), etc

current design as of 04/04 but reference latest:

![image](https://github.com/open-dollar/od-app/assets/69639595/dda8e571-80fc-4758-b10e-a3840a6cdae1)

https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=731-4373&mode=design&t=6G3HHkwuj0v3nhna-0

**Comment by pi0neerpat** [comment]
Closed by #374
