### ISSUE TITLE
OD-1 CSP Configuration

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#311]

**Comment by pi0neerpat** [comment]
Still pending to address styles

**Comment by jahabeebs** [comment]
> Still pending to address styles

@pi0neerpat 

I've tried a bunch of things to avoid having to use unsafe-inline for style-src but really I don't think it's possible with our current stack unfortunately. We can discuss it more later 

1) Tried generating nonces server-side with our bot repo and passing them into the app but this isn't feasible because we would have to pass it in at every page request (like middleware) which isn't feasible
2) Tried hardcoding the nonce into the head but this defeats the purpose of generating a nonce on each request and I still get the error "CSSStyleSheet could not be found on HTMLStyleElement"
3) Tried creating an injectNonce script that will generate a list of nonces that are dynamically switched out in our CSP which is better than option 2 but still doesn't address the fact that styled components still complains with "CSSStyleSheet could not be found on HTMLStyleElement" and it would basically break our dev environment since it relies on a postbuild command to switch out nonce in the CSP

 I pushed these changes in this branch:  https://github.com/open-dollar/od-app/tree/feature/enable-nonces-in-app 

4) Tried setting INLINE_RUNTIME_CHUNK=false both in the build script and in our .env but it did not resolve the errors mentioned above

**Comment by pi0neerpat** [comment]
Closing as complete in #317 and https://github.com/open-dollar/od-bot/pull/74
