### ISSUE TITLE
App Redesign: Cookie Consent Banner

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#316]
Designs available (04/03):

![image](https://github.com/open-dollar/od-app/assets/69639595/5a129318-288c-429f-87a7-42bce634cf27)

Figma: https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=678-1010&mode=design&t=8HiOlRgO4H3NYImh-0

**Comment by pi0neerpat** [comment]
closes #348
