### ISSUE TITLE
Fix Unit Test environment

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#320]
In #319 we needed to add tests, however our test environment is broken.

**Comment by jahabeebs** [comment]
@pi0neerpat 

I added these changes to #313 in 1632d1e3a076a12e61b3df4adc3c4b83ecf6564b

- Fixed unit test environment (bumped and added some test dependencies)
- Refactored DecimalInput component to make it easier to test the regex
- Added unit tests for some basic scenarios and tests performance 
- Pushed lint fixes

**Comment by pi0neerpat** [comment]
Done in #313
