### ISSUE TITLE
App Redesign: Confirm Transaction Modal

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#343]
Confirm transaction modal

![image](https://github.com/open-dollar/od-app/assets/47253537/e352d453-a23e-4155-b5b2-60140c768456)

Designs:  https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=678-1010&mode=design&t=76XX8JUUzbwAXQ7N-0

**Comment by pi0neerpat** [comment]
completed it #367
