### ISSUE TITLE
Cleanup onboarding

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#345]
Continued from PR #328

- [ ] Reduce font size as you see fit
- [ ] After I click the Connect Wallet button, the next screen should be shown, while the connect-wallet modal is displayed
![image](https://github.com/open-dollar/od-app/assets/35622595/e123cd2c-fc9f-4a49-b8c9-8959e514ba85)
- [ ] Currently, when the user is creating a vault facilitator, the hero section is hidden. It should be persistent: 
1. Don't hide while initializing 
![image](https://github.com/open-dollar/od-app/assets/35622595/ebee4a43-b797-478a-aa90-3adaaa2725a5)
2. Don't hide while creating vault facilitator 
![image](https://github.com/open-dollar/od-app/assets/35622595/787b3861-fcdd-4dae-b747-f8124d2124fd)

- Step bar is not showing the correct status. Eg in screen below, Step 2 should have a check showing when its complete, and the final step bubble should be filled in (no check-mark) 
![image](https://github.com/open-dollar/od-app/assets/35622595/83747af3-afbc-4a1d-8c4e-ca7547169415)
![image](https://github.com/open-dollar/od-app/assets/35622595/514e6e4a-28f7-4e36-b604-c4a40a9a1c4d)

**Comment by jahabeebs** [comment]
closed by #373
