### ISSUE TITLE
Bridge: Create UI Form Component

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#349]
### Description: 

Develop a UI component for bridging tokens. Allow users to select a token, and a originChain from 2 dropdown menus and input an optional token amount. Upon submission, compose the appropriate URL and open it in a new tab.

This UI Form will be used within a Modal, and within a Page, take that into consideration when building.

The form should take minimal props, and connect to **BridgeState** and **BridgeActions**

![image](https://github.com/open-dollar/od-app/assets/69639595/08304d69-3955-402a-8195-b4d03a186c70)

Figma Design Reference **(V3 DESIGNS)**  [Link](https://www.figma.com/file/uJdTlxdVIJNozrmGtqQQvq/OpenDollar-App?type=design&node-id=1869-2354&mode=design&t=0HTQcSm1F6VgQWCI-0)

**Comment by pi0neerpat** [comment]
Feature designs should match the new theme
![Image](https://github.com/open-dollar/od-app/assets/35622595/09e2d9ba-fc00-4914-8db0-dad2ed4ef3dc)



![Image](https://github.com/open-dollar/od-app/assets/35622595/a582063f-0743-4578-b4e3-6fb3cc655733)
