### ISSUE TITLE
Bridge: Create and Implement Bridge Modal

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#351]
### Description:
Develop a pop-up modal to prompt users to bridge tokens if they lack sufficient funds.

### They are creating a vault facilitator, but don't have funds for gas:

- No funds popup: ![Image](https://github.com/open-dollar/od-app/assets/69639595/621a8bd7-3ce0-4c36-a3e0-e062cc108e20)

- Leads to: ![Image](https://github.com/open-dollar/od-app/assets/69639595/14137152-c872-45f0-8942-9718a66aebb7)

------------------------------

### They are creating a vault, but don't have funds for collateral:

- No collateral, button to bridge: ![Image](https://github.com/open-dollar/od-app/assets/69639595/56824808-68cb-4de3-8ec7-b1267507477b)
- Popup bridge form, user enters details, enters submit which closes the bridge popup and displays the vault creation popup
- Navigate to new tab to bridge, once complete they can return and create their vault

**Comment by pi0neerpat** [comment]
Closed by #495
