### ISSUE TITLE
Shared Store State

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#366]
### Problem:

- Too many useEffects triggering each other making it very difficult/impossible to debug
- Too much duplication is state loading
- Disorganized state

### Fix:

- Create store state for shared data
- Create an init function which runs on first load and loads all necessary data
- Remove all unnecessary duplication
- Only 1 to 2 useEffects per file
- Maybe integrate reactQuery

**Comment by jahabeebs** [comment]
Closed by https://github.com/open-dollar/od-app/pull/396
