### ISSUE TITLE
od-app failed to compile on localhost

### ISSUE THREAD

**Issue by NedimRenesalis** [open-dollar/od-app#382]
I managed to seamlessly run npm install, but then npm run build produced a compilation error.

<img width="758" alt="Snimka zaslona 2024-04-21 000714" src="https://github.com/open-dollar/od-app/assets/19872990/0c424b8d-6d20-4ae8-88cc-244aebec3140">

Any ideas why?

This is a "Autogenerated file. Do not edit manually."

So there must be something else. I initially tried with node 20.12.2 as stated in the package.json, but the installation only went smooth with node 16.20.2.

**Comment by Seroxdesign** [comment]
> I managed to seamlessly run npm install, but then npm run build produced a compilation error.
> <img alt="Snimka zaslona 2024-04-21 000714" width="758" src="https://private-user-images.githubusercontent.com/19872990/324208248-0c424b8d-6d20-4ae8-88cc-244aebec3140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk3MTQsIm5iZiI6MTcxMzg3OTQxNCwicGF0aCI6Ii8xOTg3Mjk5MC8zMjQyMDgyNDgtMGM0MjRiOGQtNmQyMC00YWU4LTg4Y2MtMjQ0YWViZWMzMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEzMzY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYzkzNWFlNDA2NjJmOTEwZTU0MTE3YmNiMGY5MGUyYTJlMmQ1YjA4MmQ5YjM0Yzc1ZDgwOTQwZTRjYzJlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nP8yYt0NzKF4gZencAOBvMFvQ__LlbCggqFjydjZc0Y">
> 
> Any ideas why?
> 
> This is a "Autogenerated file. Do not edit manually."
> 
> So there must be something else. I initially tried with node 20.12.2 as stated in the package.json, but the installation only went smooth with node 16.20.2.

Hey thanks for reporting this:

- We use Yarn, not NPM that can cause issues.
- Additionally our dependencies use Node 17 & 18   I believe 20 would cause issues

let me know if there's any other issues

**Comment by Seroxdesign** [comment]
Closed due to inactivity, please reopen if issue persists.
