### ISSUE TITLE
QA - Web Redesign (Part 4)

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#384]
### Wallet View:

1.  Change button does nothing:
2. No disconnect button:
3. Transactions don't seem to appear:
![image](https://github.com/open-dollar/od-app/assets/69639595/3e840c27-d31f-4111-8db1-dd94579c6c8e)

### Add tokens to wallet, needs a hover state:

![image](https://github.com/open-dollar/od-app/assets/69639595/7022d082-9148-4082-b31c-b894c905558c)

### Warning background is too light, it should also be clickable to change the network automatically:

![image](https://github.com/open-dollar/od-app/assets/69639595/dcfaa1ee-fcaa-4a57-bcf0-3347b0e91851)

### Switching from Random chain to OD App chain causes site to break
![image](https://github.com/open-dollar/od-app/assets/69639595/0de34180-4fa6-427b-9415-6fe59df3608e)

### TOS Leads no where:
![image](https://github.com/open-dollar/od-app/assets/69639595/77d0a450-bf9a-4d3a-9e81-b62498d9529b)

### Cannot repay OD because "error calculating risk state in helper.ts 252:16". & Cannot Withdraw, deposit or borrow no error, just nothing happens
![image](https://github.com/open-dollar/od-app/assets/69639595/eeb7f73f-4685-4c32-a25e-8ed76ee33939)

**Comment by jahabeebs** [comment]
> ### Wallet View:
> 
> 
> 
> 1.  Change button does nothing:
> 
> 2. No disconnect button:
> 
> 3. Transactions don't seem to appear:
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/3e840c27-d31f-4111-8db1-dd94579c6c8e)
> 
> 
> 
> ### Add tokens to wallet, needs a hover state:
> 
> 
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/7022d082-9148-4082-b31c-b894c905558c)
> 
> 
> 
> ### Warning background is too light, it should also be clickable to change the network automatically:
> 
> 
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/dcfaa1ee-fcaa-4a57-bcf0-3347b0e91851)
> 
> 
> 
> 
> 
> ### Switching from Random chain to OD App chain causes site to break
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/0de34180-4fa6-427b-9415-6fe59df3608e)
> 
> 
> 
> 
> 
> ### TOS Leads no where:
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/77d0a450-bf9a-4d3a-9e81-b62498d9529b)
> 
> 
> 
> ### Cannot repay OD because "error calculating risk state in helper.ts 252:16". & Cannot Withdraw, deposit or borrow no error, just nothing happens
> 
> ![image](https://github.com/open-dollar/od-app/assets/69639595/eeb7f73f-4685-4c32-a25e-8ed76ee33939)
> 
> 
> 
> 

Just to clarify some things: 1 and 2 only happen when connected via a browser wallet because we can't disconnect those via the UI

Repaying is unrelated to the risk state error, the risk state log has to do with how the collateral ratio is calculated and the error logging is overly eager. The repay issue is a longstanding contract issue but not being able to withdraw or deposit or repay at all is weird so I'll need to check that

**Comment by Seroxdesign** [comment]
> Just to clarify some things: 1 and 2 only happen when connected via a browser wallet because we can't disconnect those via the UI
> 
> Repaying is unrelated to the risk state error, the risk state log has to do with how the collateral ratio is calculated and the error logging is overly eager. The repay issue is a longstanding contract issue but not being able to withdraw or deposit or repay at all is weird so I'll need to check that

Thanks for explaining, I see on 1/2

The state might have been disconnected from the buttons during redesign. Let me know if you run into any issues.

**Comment by jahabeebs** [comment]
closed by https://github.com/open-dollar/od-app/pull/387
