### ISSUE TITLE
App Redesign:  Background Image

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#394]
Step 1 - Layer the 2 graphics:
![image](https://github.com/open-dollar/od-app/assets/69639595/5d756249-b20f-4b38-ae9a-a920ac94da72)

Step 2 - If height of site is larger than the height of background asset, fix graphic to top and only show the basic background (just color no graphics).

Step 3 - Render the Rectangle at bottom footer if the total height of page is 3x the size of the rectangle below
![Rectangle 23](https://github.com/open-dollar/od-app/assets/69639595/8cf0e54a-f951-49d5-b2f8-3e543853386a)
 

Links
https://www.figma.com/file/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?type=design&node-id=216-1011&mode=design&t=P3ma24QBv3YG5BL6-0

Asset
![wavy bg](https://github.com/open-dollar/od-app/assets/69639595/33624148-f5d2-458f-9d3e-f84d687b35c8)

**Comment by alekseevaiana** [comment]
Closed by #374
