### ISSUE TITLE
Metamask fails to connect on fresh browser load

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#401]
There is an issue with a dependency https://github.com/web3-react uses: https://docs.metamask.io/wallet/how-to/connect/detect-metamask/
If 2 injected wallets exist in 1 browser, the 2nd will overwrite metamask's window.ethereum

detect-metamask will return undefined if the window.ethereum.isMetamask is false, which will cause eagerlyConnect to fail.

The only solution as of now is to refresh the browser, and it should be fully resolved.

**Comment by pi0neerpat** [comment]
Since this is a failing check in a external dependency, we can close for now. Eventually we should replace, or contribute to fix the web3-react library itself.
