### ISSUE TITLE
QA: Side menu

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#406]
- Update Side Menu font colors/sizes
![image](https://github.com/open-dollar/od-app/assets/35622595/873cb096-8a30-4404-a048-a6c6f3450036)

**Comment by alekseevaiana** [comment]
Also, 
- will add test token btn with network check
- will update available OD info. Right now if wallet is not connected, there is 0 OD in side menu, but in the full size screen when the wallet is not connected there is no info about available OD

**Comment by pi0neerpat** [comment]
If the wallet is not connected, the 0 OD should be hidden. 

![image](https://github.com/open-dollar/od-app/assets/35622595/abef7875-ca16-4d97-a4de-bd945bfe4c74)

**Comment by alekseevaiana** [comment]
Side menu on opendollar.com for some reference
![Image](https://github.com/open-dollar/od-app/assets/36742189/e7f1bd81-5e56-4ece-a5b7-984788e6b0da)

**Comment by alekseevaiana** [comment]
Closed by #429
