### ISSUE TITLE
QA: Header, test tokens

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#407]
- [x] For all networks except Arbitrum Sepolia, the test tokens button should be hidden. Appears on both the header and the mobile menu.

**Note:** Pat hide it completely it should be brought back and shown only on arb testnet.

![image](https://github.com/open-dollar/od-app/assets/35622595/47eee8fa-8b0e-4384-b8f3-284e512a15f2)
- [x] Add a slight margin to the left and right sides of the header

![image](https://github.com/open-dollar/od-app/assets/35622595/66135cd9-c4bc-4382-8137-de250c26d57e)

- [x] Remove ProxyFactory address from stats page list

**Comment by alekseevaiana** [comment]
Closed by #416
