### ISSUE TITLE
QA: Image Loading and container

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#414]
- Convert images to webp and compress
- Fix size image containers to avoid resizing
- Set up a loading state for stats page
- [ ] Add another explainer box component on the auction page under the label that says what each kind of auction is and what it does - Speak to @pi0neerpat about the text
![image](https://github.com/open-dollar/od-app/assets/69639595/210f0026-767f-4b9b-9943-e01eac06f498)

Container size: the issue is the containers will resize when an image and the text is loaded, they size (height + width) should be fixed:
![image](https://github.com/open-dollar/od-app/assets/69639595/2068991a-b5c9-4e32-9e36-5df7b9b77d91)

**Comment by alekseevaiana** [comment]
closed by #434
