### ISSUE TITLE
Feature:  Burn Button for empty Vaults.

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#426]
- Create a button on the ModifyVault page balled "Burn Vault"
- Button only visible if vault is completely empty
- Burn button will Transfer() Vault ERC721 to 0x00 burn address
- Animation will play when vault is burned (:

**Comment by pi0neerpat** [comment]
We cannot burn NFVs by sending to 0 address
![image](https://github.com/open-dollar/od-app/assets/35622595/8bf6ae44-3d2e-4ee1-a5e9-e04ff505f2e5)
