### ISSUE TITLE
Stake: UI active pools

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#430]
1. Create page "Earn"
2. Display active pools
3. Add an external link Icon on the top right, external link takes to camelot.
4. Instead of **Protocol: Camelot** put **Reward: ST-OD-ARB**
![image](https://github.com/open-dollar/od-app/assets/69639595/01705864-1b8b-4fc5-9633-5edad6b623ae)

The first pool will be OD-ETH

Can hardcode data for now

![image](https://github.com/open-dollar/od-app/assets/35622595/7266f013-83bf-4c41-a58b-b0cbc7a5f935)

**Comment by alekseevaiana** [comment]
Closed by #435
