### ISSUE TITLE
Integrate Fuul SDK for points program.

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#456]
To begin our points rewards system we need to integrate the Fuul SDK on the dapp.

Docs:
https://docs.fuul.xyz/technical-guide-for-projects/getting-started-with-the-fuul-web-sdk

Video process: https://docsend.com/view/5td7sczjnmyux39j

**Note:** Do not include signature requests for verifying wallets. 

## Frontend steps:

1. Integrate the SDK
2. Create sign functionality and page nav functionality for SDK

**Comment by pi0neerpat** [comment]
- Only trigger signing messages if the user is using a referral link
