### ISSUE TITLE
Contribute to web3-react package

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#489]
Fork the web3-react package which is responsible for the browser wallet connections

- Fix issue causing poor UX with metamask / multiple browser wallets
- Update to use EIP 6963 instead of `provider.isMetamask`

**Comment by jahabeebs** [comment]
@pi0neerpat Another issue I've found is that walletconnect does not want to give up its websocket connection (at least when using Zerion wallet) when I disconnect via my phone. Coinbase wallet does not have this problem so either it's a problem with Zerion or the library has an issue where it won't give up the connection, or we need to find a way to kill the websocket connection when switching to a different wallet (without causing a disconnect when switching to a non-wallet, Network type connection)

**Comment by pi0neerpat** [comment]
Current todo is to communicate with package maintainers about bountying a fix for this

**Comment by Seroxdesign** [comment]
![Screenshot 2024-05-31 at 08-45-02 Web3-react funding a community bounty - admin@serotonindesigns com - Seroxdesign Mail](https://github.com/open-dollar/od-app/assets/69639595/e1808b3a-0b5a-4b1f-8ba9-f548cec4a2cc)

**Comment by pi0neerpat** [comment]
Closed
