### ISSUE TITLE
New "initializing" loader

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#498]
Initializing modal should just be our loader component, without any modal

![image](https://github.com/open-dollar/od-app/assets/35622595/927058e2-34ff-4129-a88f-3b28f64d1651)

![image](https://github.com/open-dollar/od-app/assets/35622595/c349d305-6603-4399-8202-dabf1714cd77)

**Comment by alekseevaiana** [comment]
@pi0neerpat  Do we change it for all screens? I can put it instead of Modal content, so it will behave like Modal but with Loader component inside, right?

![Image](https://github.com/open-dollar/od-app/assets/36742189/47dbb0f6-8f22-4dcd-b314-faf7384123e1)
