### ISSUE TITLE
Bridge: Main interaction component

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#503]
This issue is to update the UI for the bridge component, excluding the table interaction. The table is for the next issue

![image](https://github.com/open-dollar/od-app/assets/35622595/3db27d1c-8564-40c7-9b71-f896cd9e1ce4)

- Title: Bridge
- Subtitle: `Select the asset you want to bridge to the Arbitrum network to use as a collateral of your vault.`
- Table description: `Assets on Network`

- External link icon on button. Button text: "Bridge"

![image](https://github.com/open-dollar/od-app/assets/35622595/d3c63863-57db-48c9-968a-200fad88a3fb)

- Can exclude "Powered by ..." 

- Should use the existing modal that Sero started
![image](https://github.com/open-dollar/od-app/assets/35622595/d440f034-9db7-4387-854c-9e71c7f88f3f)

**Comment by alekseevaiana** [comment]
closed by #514

**Comment by alekseevaiana** [comment]
closed by #514
