### ISSUE TITLE
Marketplace: NFV Listing Card

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#510]
### Display Data:

- NFV Index
- NFV Owner Address
- NFV Metadata Image
- Link to OpenSea Listing page
- Token Listing/Sale end date
- Dollar value of NFV = `Total Collateral dollar value - Total Debt accumulated
`
- current listing price or bid amount

### Actions:

- Button 1: Internal Link to `https://app.opendollar.com/vaults/<TokenID>`
- Button 2: External Link to `https://opensea.io/assets/arbitrum/0x0005afe00ff7e7ff83667bfe4f2996720baf0b36/<TokenID>`

**Comment by pi0neerpat** [comment]
![image](https://github.com/open-dollar/od-app/assets/35622595/662e0f79-b047-49c5-9827-570295be1b3a)

**Comment by pi0neerpat** [comment]
### Table
- [ ] The table should have features to allow filtering and sorting
- [ ] The table header should be:
- NFV Listed (showing the svg image really small)
- Asset (eg. RETH, WSTETH, ARB)
- Price (eg. "1 ETH ($3,000)")
- Estimated Value (eg. "$2,990")
- Sale Ends  (eg."In 2 days")
- Listed At (eg. "10h ago)
