### ISSUE TITLE
Bolts: token logos to be React components w/dynamic widths and heights

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-app#532]
- Our token logos used in tokens.ts are currently SVGs that have hardcoded heights and widths. We should make them react components that we can use for passing in exact heights and widths--make sure they have a default height and width in case we don't pass something in
- Test this refactoring works by going to /bolts route and refactoring the tokens to be the same height and widths to avoid this issue:

<img width="335" alt="Screenshot 2024-05-23 at 7 29 00 PM" src="https://github.com/open-dollar/od-app/assets/47253537/be38da72-3d76-46e2-a464-91b405191416">

**Comment by pi0neerpat** [comment]
Depends on https://github.com/open-dollar/od-app/pull/326

Please also update the OD and ODG icons per the new designs
