### ISSUE TITLE
Bridge: page

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#547]
- [x] Trim all assets to 4 decimals
- [x] Table of assets should always be shown. 
- [x] Add the loading spinner for asset amounts
 
![image](https://github.com/open-dollar/od-app/assets/35622595/c4ccdfa3-ba7e-4780-aef4-24b277b696ee)

- [x] Add light grey divider between rows in the table
- [x] There is a margin/gap between rows which is not click-able. This should be removed so the entire row height is clickable

![image](https://github.com/open-dollar/od-app/assets/35622595/6595d830-615a-4964-9f2c-6e3728c3493f)

- [ ] Add network icons for each item

![image](https://github.com/open-dollar/od-app/assets/35622595/bf8d1339-f8c9-40e8-a0e0-2e7ee27078b1)

- [ ] Add asset icons for each item (use existing icons)

![image](https://github.com/open-dollar/od-app/assets/35622595/5516a84b-3d94-4545-92a9-7fa0b0220754)

- [x] Lets make the network selection as tabs, rather than a dropdown. We can use the same tabs as the vault page 
![image](https://github.com/open-dollar/od-app/assets/35622595/a8d3a296-50ea-45dc-81e0-bf01f07c9ff2)

![image](https://github.com/open-dollar/od-app/assets/35622595/41e981cc-0322-4f6c-9c30-d9a76e4dd1de)

- [x] CreateVault and ModifyVault

Send the user to the bridge page instead of using a modal

**Comment by alekseevaiana** [comment]
@pi0neerpat where do we take network icons?

**Comment by pi0neerpat** [comment]
Done in #553
