### ISSUE TITLE
Fetch vault owner 

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#555]
Related to #508

Save the ownerAddress to state
- [ ] In `fetchSingleVaultData`
- [ ] When loading safes normally for the user

**Comment by jahabeebs** [comment]
> Related to #508
> 
> Save the ownerAddress to state
> 
>     * [ ]  In `fetchSingleVaultData`
> 
>     * [ ]  When loading safes normally for the user

@pi0neerpat When fetching vaults we only fetch it for the user and only hold those user's vaults in state--when a user views another user's vault then we're just fetching the single safe for that particular user. Are you saying you want to fetch the information for all the vaults in the protocol and hold that in the state?

 - [] In fetchSingleVaultData
 
This is fetched on demand when a user views someone else's vault--are you saying once they view that particular vault it should be stored in state for as long as possible?
 
- [] When loading safes normally for the user

We only fetch the vaults a user already owns (so we know the owner, it's just the user's account). We don't load other vaults until they try viewing another person's vault

**Comment by jahabeebs** [comment]
@pi0neerpat I sent this fix up to Iana's branch here, so I think we can close this. Now we can fetch any vault's owner regardless of if the wallet is connected or not. I added ownerAddress to the ISafe interface that we access via singleSafe

https://github.com/open-dollar/od-app/pull/515/commits/d02b18290076f317308ab8356f5357bc21b22cf7

## Screenshots

Wallet not connected

<img width="1442" alt="Screenshot 2024-06-13 at 3 08 17 PM" src="https://github.com/open-dollar/od-app/assets/47253537/345bae4f-86cd-4864-b3a4-213105a189af">

Wallet connected

<img width="1363" alt="Screenshot 2024-06-13 at 3 08 42 PM" src="https://github.com/open-dollar/od-app/assets/47253537/f806785a-5a26-4589-9c4d-0b6903b98792">

**Comment by pi0neerpat** [comment]
Closed in #515
