### ISSUE TITLE
Find Http courses

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#617]
HTTP, Web Services, building node.js servers, CORS

**Comment by alekseevaiana** [comment]
I will collect useful links here and at the end of the day will write another message with conclusion. 

The Hard Parts of Servers & Node.js
https://frontendmasters.com/courses/servers-node-js/

Web Performance Fundamentals
https://frontendmasters.com/courses/web-perf/

Cashing
https://frontendmasters.com/courses/web-performance/caching/

CORS
https://www.classcentral.com/classroom/youtube-cross-origin-resource-sharing-explained-by-example-139403

**Comment by alekseevaiana** [comment]
Decided to start with The Hard Parts of Servers & Node.js (interesting)
https://frontendmasters.com/courses/servers-node-js/

**Comment by pi0neerpat** [comment]
Done
