### ISSUE TITLE
QA - Menu 

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#76]
- [ ] On mobile, logo is too small

![image](https://github.com/UseKeyp/od-app/assets/35622595/83aa146f-0596-4a82-b394-57e4671ba44f)

- [ ] Mobile menu: remove top section "welcome to reflexer section"

![image](https://github.com/UseKeyp/od-app/assets/35622595/b6ed7123-ad87-4ed4-aa88-44415d7dddaa)

- [ ] Mobile menu: remove icons for each link
- [ ] Mobile menu: add ability to close the menu bar with "X" icon in the top right
- [ ] Mobile menu: add OD market price, OD balance
![image](https://github.com/UseKeyp/od-app/assets/35622595/27cb0806-82c0-4a41-bd0f-183d0f4dec66)

- [ ] (Sascha) Token balance updates 
     - should be a wallet icon, not the token icon 
     - change to dropdown, instead of "add" button
     - Click to add token to wallet
![image](https://github.com/UseKeyp/od-app/assets/35622595/2a6c525b-270e-4b45-872e-2de121d3d200)

**Comment by jahabeebs** [comment]
> * [ ]  On mobile, logo is too small
> 
> 
> ![image](https://user-images.githubusercontent.com/35622595/262439280-83aa146f-0596-4a82-b394-57e4671ba44f.png)
> 
>     * [ ]  Mobile menu: remove top section "welcome to reflexer section"
> 
> 
> ![image](https://user-images.githubusercontent.com/35622595/262439447-b6ed7123-ad87-4ed4-aa88-44415d7dddaa.png)
> 
>     * [ ]  Mobile menu: remove icons for each link
> 
>     * [ ]  Mobile menu: add ability to close the menu bar with "X" icon in the top right
> 
>     * [ ]  Mobile menu: add OD market price, OD balance
>       ![image](https://user-images.githubusercontent.com/35622595/263376728-27cb0806-82c0-4a41-bd0f-183d0f4dec66.png)
> 
>     * [ ]  (Sascha) Token balance updates
>       
>       * should be a wallet icon, not the token icon
>       * change to dropdown, instead of "add" button
>       * Click to add token to wallet
>         ![image](https://user-images.githubusercontent.com/35622595/263376788-2a6c525b-270e-4b45-872e-2de121d3d200.png)

@pi0neerpat By "click to add token to wallet" do you mean that text should be added? If so, it's added in the dropdown when clicking the arrow?

**Comment by pi0neerpat** [comment]
See designs. Adding token using the ethers request

https://docs.metamask.io/wallet/how-to/display/tokens/

<img width="276" alt="image" src="https://github.com/open-dollar/od-app/assets/35622595/76200242-3f5a-4d89-b458-388fb42086c3">
